-- Create templates table
CREATE TABLE IF NOT EXISTS public.templates (
    id text PRIMARY KEY,
    title text NOT NULL,
    description text,
    type text DEFAULT 'template',
    likes text,
    src text NOT NULL,
    is_local_video boolean DEFAULT false,
    media_type text DEFAULT 'image',
    category text DEFAULT 'trends',
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    fields jsonb,
    required_files_count integer DEFAULT 1
);

-- Enable RLS
ALTER TABLE public.templates ENABLE ROW LEVEL SECURITY;

-- Policy for reading (public)
DROP POLICY IF EXISTS "Templates are viewable by everyone" ON public.templates;
CREATE POLICY "Templates are viewable by everyone" ON public.templates
    FOR SELECT USING (true);

-- Insert data
INSERT INTO public.templates (id, title, description, type, likes, src, is_local_video, media_type, category, fields, required_files_count)
VALUES
    ('trend_dance', 'Трендовый танец', 'Сгенерируй танец из этих ваших Тиктоков!', 'template', '15k', '/videos/dance_trend.mp4', true, 'video', 'dances', null, 1),
    ('lezginka', 'ЛЕЗГИНКА', 'Сгенерируй Лезгинку на любом фото!', 'template', '10k', '/videos/lezginka.mp4', true, 'video', 'dances', null, 1),
    ('macarena', 'МАКАРЕНА', 'Сгенерируй трендовый танец с любого фото', 'template', '12k', '/videos/macarena.mp4', true, 'video', 'dances', null, 1),
    ('michael_jackson', 'МАЙКЛ ДЖЕКСОН', 'Сгенерируй трендовый танец с любого фото', 'template', '20k', '/videos/michael_jackson.mp4', true, 'video', 'dances', null, 1),
    ('moscow', 'MOSCOW', 'Сгенерируй танец на любом фото!', 'template', '8k', '/videos/moscow.mp4', true, 'video', 'dances', null, 1),
    ('generations_portrait', 'ПОРТРЕТ ПОКОЛЕНИЙ', 'Портрет поколений', 'template', '25k', '/images/generations_portrait.jpeg', false, 'image', 'trends', '[{"id": "gen_desc", "type": "text", "label": "Описание поколений", "placeholder": "Например: Бабушка, Мама, Дочь"}]', 1),
    ('universal_portrait', 'УНИВЕРСАЛЬНЫЙ ПОРТРЕТ', 'Универсальный портрет', 'template', '30k', '/images/universal_portrait.jpeg', false, 'image', 'trends', null, 1),
    ('hairstyle_change', 'СМЕНА ПРИЧЕСКИ', 'Примерь новый образ', 'template', '18k', '/images/hairstyle_change.jpeg', false, 'image', 'trends', null, 1),
    ('sun_rays', 'СОЛНЕЧНЫЕ ЛУЧИ', 'Красивая фотография в солнечных лучах', 'template', '35k', '/images/sun_rays.jpeg', false, 'image', 'trends', null, 1),
    ('polaroid_hugs', 'ПАЛАРОИД ОБНИМАШКИ', 'нужно. 2 фото', 'template', '22k', '/images/polaroid_hugs.jpeg', false, 'image', 'trends', null, 2),
    ('future_partner', 'БУДУЩАЯ ПАРА', 'Узнай с кем будешь', 'template', '40k', '/videos/future_partner.mp4', true, 'video', 'trends', null, 1),
    ('animate_photo', 'ОЖИВИТЬ ФОТО', 'Оживите ваши фотографии', 'template', '50k', '/videos/animate_photo.mp4', true, 'video', 'trends', '[{"id": "anim_prompt", "type": "text", "label": "Действие", "placeholder": "Улыбнуться, подмигнуть..."}]', 1),
    ('patronus', 'ПАТРОНУС', 'Узнай свой патронус', 'template', '33k', '/images/patronus.jpeg', false, 'image', 'trends', null, 1),
    ('snow_queen', 'СНЕЖНАЯ КОРОЛЕВА', 'Вы — в образе Снежной королевы', 'template', '28k', '/images/snow_queen.jpeg', false, 'image', 'trends', null, 1),
    ('lego_effect', 'LEGO', 'Эффект LEGO из фото', 'template', '55k', '/images/lego_effect.jpeg', false, 'image', 'trends', null, 1),
    ('tokyo_style', 'TOKYO STYLE', 'BMW M3 GTR в Токио', 'template', '48k', '/images/tokyo_style.jpeg', false, 'image', 'trends', null, 1),
    ('knitted_effect', 'ВЯЗАНЫЙ ЭФФЕКТ', 'Уютный вязаный стиль', 'template', '15k', '/images/knitted_effect.jpeg', false, 'image', 'trends', null, 1),
    ('flash_effect', 'ЭФФЕКТ ВСПЫШКИ', 'Яркая вспышка', 'template', '12k', '/images/flash_effect.jpeg', false, 'image', 'trends', null, 1),
    ('passport_photo', 'ФОТО НА ПАСПОРТ', 'Классика, черный пиджак', 'template', '9k', '/images/passport_photo.jpeg', false, 'image', 'trends', null, 1),
    ('age_test', 'ТЕСТ НА ВОЗРАСТ', 'Узнай свой возраст', 'template', '60k', '/images/age_test.jpeg', false, 'image', 'trends', null, 1),
    ('nyc_style', 'НЬЮ ЙОРК СТИЛЬ', 'Атмосфера большого города', 'template', '34k', '/images/nyc_style.jpeg', false, 'image', 'trends', null, 1),
    ('sticker_no_text', 'СТИКЕР', 'Стикер без текста', 'template', '20k', '/images/sticker_no_text.jpeg', false, 'image', 'trends', null, 1),
    ('soviet_tree', 'СОВЕТСКАЯ ЕЛКА', 'Ретро стиль', 'template', '27k', '/images/soviet_tree.jpeg', false, 'image', 'trends', null, 1),
    ('polaroid_cheburashka', 'ПОЛАРОИД ЧЕБУРАШКА', 'Гена и Чебурашка', 'template', '31k', '/images/polaroid_cheburashka.jpeg', false, 'image', 'trends', null, 1),
    ('beard_style', 'БОРОДА И УСЫ', 'Смена имиджа', 'template', '22k', '/images/beard_style.jpeg', false, 'image', 'trends', null, 1),
    ('monster_high', 'КУКЛА MONSTER HIGH', 'Стиль куклы', 'template', '45k', '/images/monster_high.jpeg', false, 'image', 'trends', null, 1),
    ('bw_lady', 'B&W LADY', 'Нуар портрет', 'template', '28k', '/images/bw_lady.jpeg', false, 'image', 'trends', null, 1),
    ('sunset_field', 'ПОЛЕ НА ЗАКАТЕ', 'Романтика', 'template', '33k', '/images/sunset_field.jpeg', false, 'image', 'trends', null, 1),
    ('beach_portrait', 'НА ПЛЯЖЕ', 'Золотой час', 'template', '30k', '/images/beach_portrait.jpeg', false, 'image', 'trends', null, 1),
    ('ray_portrait', 'ПОРТРЕТ С ЛУЧОМ', 'Минимализм', 'template', '25k', '/images/ray_portrait.jpeg', false, 'image', 'trends', null, 1),
    ('bw_man', 'B&W MAN', 'Нуар портрет', 'template', '27k', '/images/bw_man.jpeg', false, 'image', 'trends', null, 1),
    ('summer_corset', 'ЛЕТНИЙ ПОРТРЕТ', 'Легкость и красота', 'template', '29k', '/images/summer_corset.jpeg', false, 'image', 'trends', null, 1),
    ('old_year_card', 'ОТКРЫТКА - СТАРЫЙ ГОД', 'Открытка - старый год', 'template', '18k', '/images/old_year_card.jpeg', false, 'image', 'christmas', null, 1),
    ('old_year_card_2', 'ОТКРЫТКА - СТАРЫЙ ГОД v2', 'Вариант 2', 'template', '16k', '/images/old_year_card.jpeg', false, 'image', 'christmas', null, 1),
    ('polaroid_tree', 'ПОЛАРОИД ЕЛКА', 'Уютное фото у елки', 'template', '14k', '/images/polaroid_tree.jpeg', false, 'image', 'christmas', null, 1),
    ('christmas_card_custom', 'РОЖДЕСТВЕНСКАЯ ОТКРЫТКА', 'Создайте свою открытку', 'template', '19k', '/images/christmas_card_custom.jpeg', false, 'image', 'christmas', null, 1),
    ('photo_in_toy', 'ФОТО В ИГРУШКЕ', 'Ваше фото в елочном шаре', 'template', '21k', '/images/photo_in_toy.jpeg', false, 'image', 'christmas', null, 1),
    ('irony_of_fate', 'ИРОНИЯ СУДЬБЫ', 'Почувствуй атмосферу фильма', 'template', '25k', '/images/irony_of_fate.jpeg', false, 'image', 'christmas', null, 1),
    ('new_year_card', 'НОВОГОДНЯЯ ОТКРЫТКА', 'Поздравьте близких', 'template', '17k', '/images/new_year_card.jpeg', false, 'image', 'christmas', null, 1),
    ('harry_potter_card', 'ОТКРЫТКА ГАРРИ ПОТТЕР', 'Магическая открытка', 'template', '40k', '/images/harry_potter_card.jpeg', false, 'image', 'christmas', null, 1),
    ('christmas_toy', 'ЕЛОЧНАЯ ИГРУШКА', 'Сделай игрушку из фото', 'template', '22k', '/images/christmas_toy.jpeg', false, 'image', 'christmas', null, 1),
    ('figure_in_sphere', 'ФИГУРКА В ШАРЕ', 'Зимняя сказка', 'template', '18k', '/images/figure_in_sphere.jpeg', false, 'image', 'christmas', null, 1),
    ('satin_gloss', 'САТИНОВЫЙ ГЛЯНЕЦ', 'Зимняя фотосессия', 'template', '32k', '/images/satin_gloss.png', false, 'image', 'christmas', null, 1),
    ('christmas_glamour', 'РОЖДЕСТВЕНСКИЙ ГЛАМУР', 'Праздничный шик', 'template', '28k', '/images/christmas_glamour.png', false, 'image', 'christmas', null, 1),
    ('snow_globe', 'СНЕЖНЫЙ ШАР', 'Волшебство внутри', 'template', '35k', '/images/snow_globe.jpeg', false, 'image', 'christmas', null, 1),
    ('festive_portrait', 'ПРАЗДНИЧНЫЙ ПОРТРЕТ', 'Ваш новогодний образ', 'template', '24k', '/images/festive_portrait.png', false, 'image', 'christmas', null, 1),
    ('christmas_car', 'РОЖДЕСТВЕНСКОЕ АВТО', 'Праздник в пути', 'template', '20k', '/images/christmas_car.jpeg', false, 'image', 'christmas', null, 1),
    ('garage_tale', 'ГАРАЖНАЯ СКАЗКА', 'Уютный зимний гараж', 'template', '16k', '/images/garage_tale.png', false, 'image', 'christmas', null, 1),
    ('golden_portrait', 'ЗОЛОТОЙ КИНОПОРТРЕТ', 'Блеск золота', 'template', '38k', '/images/golden_portrait.jpeg', false, 'image', 'christmas', null, 1),
    ('nutcracker', 'ЩЕЛКУНЧИК', 'Сказочный герой', 'template', '27k', '/images/nutcracker.png', false, 'image', 'christmas', null, 1),
    ('bordeaux_couture', 'БОРДО КУТЮР', 'Стильный красный', 'template', '23k', '/images/bordeaux_couture.png', false, 'image', 'christmas', null, 1),
    ('car_in_snow', 'АВТО В СНЕГУ', 'Зимняя дорога', 'template', '26k', '/images/car_in_snow.png', false, 'image', 'christmas', null, 1),
    ('festive_gloss', 'ПРАЗДНИЧНЫЙ ГЛЯНЕЦ', 'Обложка журнала', 'template', '30k', '/images/festive_gloss.png', false, 'image', 'christmas', null, 1),
    ('angels_inspire', 'ВДОХНОВЕНИЕ', 'Ангельское вдохновение', 'template', '25k', '/images/angels_inspire.jpeg', false, 'image', 'angels', null, 1),
    ('angels_whisper', 'ШЕПОТ СЕРДЦА', 'Тихий шепот ангела', 'template', '21k', '/images/angels_whisper.jpeg', false, 'image', 'angels', null, 1),
    ('angels_silence', 'ТИШИНА ВНУТРИ', 'Светлая тишина', 'template', '18k', '/images/angels_silence.jpeg', false, 'image', 'angels', null, 1),
    ('angels_pulse', 'ЛЕГКОЕ БИЕНИЕ', 'Ритм сердца', 'template', '15k', '/images/angels_pulse.jpeg', false, 'image', 'angels', null, 1),
    ('angels_sign', 'ЗНАК СВЕТА', 'Божественный знак', 'template', '29k', '/images/angels_sign.jpeg', false, 'image', 'angels', null, 1),
    ('car_crush', 'АВТО КРУШИТ ГОРОД', 'Гигантское авто', 'template', '45k', '/images/car_crush.jpeg', false, 'image', 'cars', null, 1),
    ('hot_wheels_hand', 'HOT WHEELS В РУКЕ', 'Твое авто - моделька', 'template', '50k', '/images/hot_wheels_hand.jpeg', false, 'image', 'cars', null, 1),
    ('street_car', 'STREET CAR', 'Ночной уличный гонщик', 'template', '42k', '/images/street_car.jpeg', false, 'image', 'cars', null, 1),
    ('car_flower_street', 'АВТО НА УЛОЧКЕ', 'Красивая улица с цветами', 'template', '36k', '/images/car_flower_street.jpeg', false, 'image', 'cars', null, 1),
    ('car_paparazzi', 'ФОТКАЮТ ТАЧКУ', 'В центре внимания', 'template', '39k', '/images/car_paparazzi.jpeg', false, 'image', 'cars', null, 1),
    ('zombie_car', 'ЗОМБИ ВОКРУГ АВТО', 'Апокалипсис', 'template', '44k', '/images/zombie_car.jpeg', false, 'image', 'cars', null, 1),
    ('nfs_race', 'NFS ГОНКА', 'Жажда скорости', 'template', '55k', '/images/nfs_race.jpeg', false, 'image', 'cars', null, 1),
    ('car_model', 'МОДЕЛЬКА АВТО', 'Игрушечная копия', 'template', '33k', '/images/car_model.jpeg', false, 'image', 'cars', null, 1),
    ('pet_moon', 'ПИТОМЕЦ С ЛУНОЙ', 'Волшебная сцена', 'template', '40k', '/images/pet_moon.jpeg', false, 'image', 'pets', null, 1),
    ('pet_hero', 'ПИТОМЕЦ-СУПЕРГЕРОЙ', 'Защитник города', 'template', '38k', '/images/pet_moon.jpeg', false, 'image', 'pets', null, 1),
    ('pet_bath', 'ПИТОМЕЦ В ВАННОЙ', 'Милая сцена', 'template', '42k', '/images/pet_bath.jpeg', false, 'image', 'pets', null, 1),
    ('pet_office', 'ПИТОМЕЦ В ОФИСЕ', 'Трудовые будни', 'template', '35k', '/images/pet_office.jpeg', false, 'image', 'pets', null, 1),
    ('pet_vogue', 'НА ОБЛОЖКЕ VOGUE', 'Пафосный кот', 'template', '50k', '/images/pet_vogue.jpeg', false, 'image', 'pets', null, 1),
    ('scream_girl', 'КРИК (ДЕВУШКИ)', 'Кадр из фильма', 'template', '33k', '/images/scream_girl.png', false, 'image', 'oldTrends', null, 1),
    ('peephole', 'ГЛАЗОК', 'Фото в глазок', 'template', '28k', '/images/peephole.jpeg', false, 'image', 'oldTrends', null, 1),
    ('scream_style', 'СТИЛЬ С КРИКОМ', 'Красный фон', 'template', '30k', '/images/scream_style.jpeg', false, 'image', 'oldTrends', null, 1),
    ('figure_style', 'ФИГУРКА', 'Твоя копия', 'template', '27k', '/images/figure_style.jpeg', false, 'image', 'oldTrends', null, 1),
    ('trump_potato', 'ТРАМП НА ОГОРОДЕ', 'Копаем картошку', 'template', '55k', '/images/trump_potato.jpeg', false, 'image', 'oldTrends', null, 1),
    ('giant_sushi', 'ГИГАНТСКИЙ СУШИ', 'Высокая мода', 'template', '32k', '/images/giant_sushi.jpeg', false, 'image', 'oldTrends', null, 1),
    ('motion_crowd', 'МОУШН В ТОЛПЕ', 'Движение города', 'template', '29k', '/images/motion_crowd.jpeg', false, 'image', 'oldTrends', null, 1),
    ('dark_queen', 'КОРОЛЕВА ТЬМЫ', 'Правительница теней', 'template', '44k', '/images/dark_queen.jpeg', false, 'image', 'oldTrends', null, 1),
    ('statue_style', 'СТАТУЯ', 'Ожившая статуя', 'template', '31k', '/images/statue_style.jpeg', false, 'image', 'oldTrends', null, 1),
    ('scream_boy', 'КРИК (ПАРНИ)', 'Кадр из фильма', 'template', '30k', '/images/scream_boy.png', false, 'image', 'oldTrends', null, 1)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    likes = EXCLUDED.likes,
    src = EXCLUDED.src,
    is_local_video = EXCLUDED.is_local_video,
    media_type = EXCLUDED.media_type,
    category = EXCLUDED.category,
    fields = EXCLUDED.fields,
    required_files_count = EXCLUDED.required_files_count;
