ALTER TABLE creations ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'success';
ALTER TABLE creations ADD COLUMN IF NOT EXISTS error_message TEXT;
ALTER TABLE creations ALTER COLUMN image_url DROP NOT NULL;
ALTER TABLE creations ADD COLUMN IF NOT EXISTS cost INTEGER DEFAULT 0;
