-- Create Chats table
CREATE TABLE IF NOT EXISTS chats (
    id TEXT PRIMARY KEY, -- Internal UUID or External ID if guaranteed unique
    platform TEXT NOT NULL, -- 'yandex', 'digiseller', etc.
    external_id TEXT NOT NULL, -- ID from the platform
    client_name TEXT,
    last_message TEXT,
    unread_count INTEGER DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    metadata JSONB DEFAULT '{}'::jsonb,
    UNIQUE(platform, external_id)
);

-- Create Messages table
CREATE TABLE IF NOT EXISTS chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id TEXT REFERENCES chats(id) ON DELETE CASCADE,
    external_message_id TEXT,
    text TEXT,
    sender TEXT, -- 'client', 'shop', 'system'
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    platform_data JSONB DEFAULT '{}'::jsonb
);

-- Add platform columns to orders if missing
ALTER TABLE orders ADD COLUMN IF NOT EXISTS platform TEXT DEFAULT 'manual';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS external_id TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS extra_data JSONB DEFAULT '{}'::jsonb;

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_chats_platform_external ON chats(platform, external_id);
CREATE INDEX IF NOT EXISTS idx_orders_platform_external ON orders(platform, external_id);
